require 'bundler/setup'
require 'rubocop/rake_task'
require 'rake/testtask'

task default: :rubocop

RuboCop::RakeTask.new

desc 'Run integration tests'
Rake::TestTask.new(:integration) do |test|
  test.test_files = FileList['test/**/integration/test_*.rb']
  test.warning = false
end

desc 'Run unit tests'
Rake::TestTask.new(:test) do |task|
  task.test_files = FileList['test/**/unit/test_*.rb']
  task.warning = false
end

desc 'Run application in the development mode'
task :run do
  ruby 'app.rb'
end
